### PR TITLE
chore: release version 2.2.0

### PR DESCRIPTION
**Pull request by brandyscarney**
Minor release due to adding the following: https://github.com/ionic-team/prettier-config/commit/dbdbb21df505d505287fef17e6c82455a9a0cf0f

### CODE REVIEW

**Comment by rwaskiewicz** [comment]
Gonna give this a test in Stencil repos real quick

**Comment by brandyscarney** [comment]
FWIW I don't think this will have any effect on our internal projects since we don't include `md` files in the prettier commands here: 

- [framework](https://github.com/ionic-team/ionic-framework/blob/main/core/package.json#L88)
- [stencil](https://github.com/ionic-team/stencil/blob/main/package.json#L32)
- [capacitor](https://github.com/ionic-team/capacitor/blob/main/package.json#L21)

But it should be better to target this as a minor anyway

**Review by rwaskiewicz — APPROVED** [review]
To @brandyscarney's point, Stencil doesn't fmt any markdown files ATM.

I do have a [JEDI day project where I get Prettier running on the Stencil Doc site](https://github.com/ionic-team/stencil-site/pull/1047) that I've been neglecting to land. I installed this branch's version of `@ionic/prettier-config` in that Stencil Doc Site branch and got the following differences vs v2.1.2:

```diff
diff --git a/docs/reference/browser-support.md b/docs/reference/browser-support.md
index 8aae1c62d..2c3e634d7 100644
--- a/docs/reference/browser-support.md
+++ b/docs/reference/browser-support.md
@@ -18,7 +18,7 @@ Stencil builds Web Components that run natively or near-natively in all widely u
       </div>
       <div className="bs-chart__card">
         <ion-icon name="checkmark"></ion-icon>
-        Safari 14+  
+        Safari 14+
       </div>
       <div className="bs-chart__card">
         <ion-icon name="checkmark"></ion-icon>
@@ -29,9 +29,7 @@ Stencil builds Web Components that run natively or near-natively in all widely u
         Edge 79+
       </div>
     </div>
-    <div className="bs-chart__group-label">
-      Full native support
-    </div>
+    <div className="bs-chart__group-label">Full native support</div>
   </div>
   <div className="bs-chart__group">
     <div className="bs-chart__cards">
@@ -40,9 +38,7 @@ Stencil builds Web Components that run natively or near-natively in all widely u
         IE 11, Edge 16-18
       </div>
     </div>
-    <div className="bs-chart__group-label">
-      Deprecated in Stencil v3.
-    </div>
+    <div className="bs-chart__group-label">Deprecated in Stencil v3.</div>
   </div>
 </div>
 
diff --git a/docs/reference/versioning.md b/docs/reference/versioning.md
index 79ff44a68..bfbf2d76b 100644
--- a/docs/reference/versioning.md
+++ b/docs/reference/versioning.md
@@ -8,9 +8,11 @@ slug: /versioning
 # Versioning
 
 Stencil follows the <a href="https://semver.org/" target="_blank">Semantic Versioning (SemVer)</a> convention:
-<code>major.minor.patch.</code> Incompatible API changes increment the <code>major</code> version, adding
-backwards-compatible functionality increments the <code>minor</code> version, and backwards-compatible bug fixes
-increment the <code>patch</code> version.
+
+<code>major.minor.patch.</code> Incompatible API changes increment the <code>major</code> version, adding backwards-compatible
+functionality increments the <code>minor</code> version, and backwards-compatible bug fixes increment the <code>
+  patch
+</code> version.
 
 ## Release Schedule
```

So like most Prettier-related releases, there can be "breaking changes" in a minor release. So long as we're OK with that, so am I. I'd probably vote for this being a major version bump, but that's just my 2C 🤷

**Comment by brandyscarney** [comment]
Closing to release as a major

**Pull request closed without merging**
